name: Assessment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
permissions: write-all
jobs:
  assess:
    name: Assess
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      # Install required packages
      - name: Install packages
        run: |
          pip3 install -r ./days_api/requirements.txt
          pip3 install pytest pylint
      # Run pytest
      - name: Run tests
        continue-on-error: true
        run: pytest
      # Write Pytest overview results to a file
      - name: Record test results
        if: '!cancelled()'
        run: |
          pytest -r N --tb=no > .util/marking.txt || true
      # Run pylint
      - name: Run linter
        if: '!cancelled()'
        continue-on-error: true
        run: pylint --fail-under=8 ./days_api/*.py --ignore-patterns "test_.+.py"
      # Write Pylint overview results to a file
      - name: Record linter results
        if: '!cancelled()'
        run: |
          pylint --fail-under=0 --score=y --reports=n */*.py >> .util/marking.txt || true
      # Convert results to JSON
      - name: Convert result format
        if: '!cancelled()'
        run: |
          cd .util
          python3 convert_to_json.py
      # Commit results
      - name: Push results
        if: '!cancelled()'
        run: |
          git config --global user.name 'Peritract'
          git config --global user.email 'peritract@users.noreply.github.com'
          git add .util/marking.txt .util/marking.json
          git commit -m "Assessment testing"
          git push
